# Generated by Django 5.2.5 on 2025-08-31 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_createblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 31, 11, 40, 3, 615190, tzinfo=datetime.timezone.utc)),
        ),
    ]
