# Generated by Django 5.2.5 on 2025-09-08 09:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_bio_user_profile_alter_createblog_ttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 9, 4, 54, 96012, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttime', models.DateTimeField(default=datetime.datetime(2025, 9, 8, 9, 4, 54, 96625, tzinfo=datetime.timezone.utc))),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.createblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
