# Generated by Django 5.2.5 on 2025-09-08 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_createblog_ttime_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='car',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='createblog',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 9, 47, 19, 486550, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 9, 47, 19, 487179, tzinfo=datetime.timezone.utc)),
        ),
    ]
