# Generated by Django 5.2.5 on 2025-09-08 13:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_car_wishlist_blog_alter_createblog_ttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 13, 50, 16, 851245, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 13, 50, 16, 852221, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Likeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.createblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
