# Generated by Django 5.2.5 on 2025-09-08 14:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_createblog_ttime_alter_wishlist_ttime_likeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 14, 15, 24, 259149, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 14, 15, 24, 260353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DisLikeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.createblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
